### ISSUE TITLE
Laravel 5.3 Compatability

### ISSUE THREAD

**Issue by ScottPhillips** [tehcodedninja/TeamRoles#1]
Any plans on updating this for Laravel 5.3?

Thanks!

**Comment by codedninja** [comment]
I made this in Laravel 5.3, what are the issues you are having with 5.3 compatability?

**Comment by ScottPhillips** [comment]
Hmmm, my bad, it wasn't a Laravel compatability issue, but composer gives me this error when I add "tehcodedninja/teamroles": "1.1.0":

 - The requested package tehcodedninja/teamroles 1.1.0 exists as tehcodedninja/teamroles[1.0.3-alpha, dev-master] but these are rejected by your constraint.

**Comment by codedninja** [comment]
Sorry about that, fixed the README.md should be good to download.
